import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ExternalLink,CheckCircle2,Clock3,AlertTriangle,Filter} from 'lucide-react';
import {products} from './data';
import './styles.css';
const KEY='pesquisa-produtos-v1';
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
function App(){const[records,setRecords]=useState(load),[q,setQ]=useState(''),[status,setStatus]=useState('Todos');const update=(id,patch)=>{const n={...records,[id]:{...(records[id]||{}),...patch}};setRecords(n);save(n)};const list=useMemo(()=>products.filter(p=>(p.name.toLowerCase().includes(q.toLowerCase())||String(p.id)===q)&&(status==='Todos'||(records[p.id]?.status||'Pendente')===status)),[q,status,records]);const counts=useMemo(()=>products.reduce((a,p)=>{const s=records[p.id]?.status||'Pendente';a[s]=(a[s]||0)+1;return a},{}),[records]);return <div className='app'><header><div><h1>Pesquisa de Produtos</h1><p>Catálogo da loja · {products.length} produtos</p></div><div className='stats'><b>{counts.Encontrado||0}</b> encontrados · <b>{counts.Pendente||0}</b> pendentes</div></header><section className='toolbar'><div className='search'><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Pesquisar produto...'/></div><div className='filters'><Filter size={16}/>{['Todos','Pendente','Encontrado','Revisar','Descartado'].map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s}</button>)}</div></section><main>{list.map(p=><Card key={p.id} p={p} rec={records[p.id]||{}} update={update}/>)}</main>{!list.length&&<div className='empty'>Nenhum produto encontrado.</div>}</div>}
function Card({p,rec,update}){const s=rec.status||'Pendente';return <article className='card'><div className='photo'>{p.image?<img src={p.image} alt='' loading='lazy'/>:<span>Sem imagem</span>}</div><div className='info'><div className='top'><span className='id'>#{p.id}</span><span className={'badge '+s.toLowerCase()}>{s==='Encontrado'?<CheckCircle2 size={14}/>:s==='Revisar'?<AlertTriangle size={14}/>:<Clock3 size={14}/>} {s}</span></div><h2>{p.name}</h2><div className='cost'>Custo: <strong>R$ {Number(p.cost).toFixed(2).replace('.',',')}</strong></div><div className='fields'><input value={rec.foundName||''} onChange={e=>update(p.id,{foundName:e.target.value})} placeholder='Nome encontrado'/><select value={rec.platform||''} onChange={e=>update(p.id,{platform:e.target.value})}><option value=''>Plataforma/site</option><option>Mercado Livre</option><option>Shopee</option><option>SHEIN</option><option>Outro</option></select><input value={rec.price||''} onChange={e=>update(p.id,{price:e.target.value})} placeholder='Preço encontrado'/><input value={rec.url||''} onChange={e=>update(p.id,{url:e.target.value})} placeholder='Link do anúncio'/><select value={s} onChange={e=>update(p.id,{status:e.target.value})}><option>Pendente</option><option>Encontrado</option><option>Revisar</option><option>Descartado</option></select><input value={rec.note||''} onChange={e=>update(p.id,{note:e.target.value})} placeholder='Observação / confiança'/></div>{rec.url&&<a className='open' href={rec.url} target='_blank' rel='noreferrer'>Abrir anúncio <ExternalLink size={15}/></a>}</div></article>}
createRoot(document.getElementById('root')).render(<App/>);
